#!/bin/bash


python train.py --data_dir ./Plane_train.csv --model_dir ./model_plane_0409 --learning_rate 1e-4 --decay_rate 0.9;
#python train.py --data_dir ./Plane_train.csv --model_dir ./model_plane_0609 --learning_rate 1e-6 --decay_rate 0.9;
#python train.py --data_dir ./Plane_train.csv --model_dir ./model_plane_0407 --learning_rate 1e-4 --decay_rate 0.7;
#python train.py --data_dir ./Plane_train.csv --model_dir ./model_plane_0607 --learning_rate 1e-6 --decay_rate 0.7;
#python train.py --data_dir ./Plane_train.csv --model_dir ./model_plane_0507 --learning_rate 1e-5 --decay_rate 0.7;
#python train.py --data_dir ./Plane_train.csv --model_dir ./model_plane_0509 --learning_rate 1e-5 --decay_rate 0.9;

#python train.py --data_dir ./Plane_train.csv --model_dir ./model_plane;
#python train.py --data_dir ./Butterfly_train.csv --model_dir ./model_butterfly;
#python train.py --data_dir ./DogJump_train.csv --model_dir ./model_dog;
#python train.py --data_dir ./Giraffe_train.csv --model_dir ./model_giraffe;


